CREATE TABLE IF NOT EXISTS app_data (
  id INT PRIMARY KEY DEFAULT 1,
  payload JSON NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- MySQL 5.7/8.x: se o seu host não aceitar JSON, use LONGTEXT:
-- CREATE TABLE IF NOT EXISTS app_data (
--   id INT PRIMARY KEY DEFAULT 1,
--   payload LONGTEXT NOT NULL,
--   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
