CREATE TABLE IF NOT EXISTS app_data (
  id INT AUTO_INCREMENT PRIMARY KEY,
  payload JSON NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Versão compatível com MySQL 5.7/8.x
-- Se o seu servidor não suportar JSON, use LONGTEXT em vez de JSON:
-- CREATE TABLE IF NOT EXISTS app_data (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   payload LONGTEXT NOT NULL,
--   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
